name: Deploy users-auth QA

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    name: Deploy to EC2 QA
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/users-auth
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
